In [34]:
%load_ext autoreload
%autoreload 2

%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import pinv

import mdpy as mdp

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [35]:
P = np.array([
        [0.1, 0.9], 
        [0.5, 0.5]])

ns = len(P)

D = np.diag(mdp.stationary(P))

In [36]:
mdp.linalg.approx_stationary([[0.1, 0.9], [0.5, 0.5]])

array([ 0.35714525,  0.64285475])

In [37]:
mdp.stationary(P)

array([ 0.35714286,  0.64285714])

In [38]:
mdp.potential(0.9*P)

array([[ 4.04411765,  5.95588235],
       [ 3.30882353,  6.69117647]])

In [39]:
I = np.eye(ns)

G = np.diag(np.ones(ns)*0.9)
L = np.diag(np.ones(ns)*0.0)
X = np.identity(ns)
ivec = np.ones(ns)
r = np.array([0.9, 0])

In [40]:
mdp.bellman(P, G, r)

array([ 3.63970588,  2.97794118])

In [41]:
mdp.least_squares(P, G, X, r)

array([ 3.63970588,  2.97794118])

In [42]:
mdp.td_solution(P, G, L, X, r)

array([ 3.63970588,  2.97794118])

In [43]:
mdp.etd_solution(P, G, L, X, ivec, r)

array([ 3.63970588,  2.97794118])

In [44]:
# The equation for TD(0)'s weights
pinv(X.T @ D @ mdp.potential(P @ G) @ X) @ X.T @ D @ r

array([ 0.819, -0.405])

In [45]:
# the equation for least squares weights
pinv(X.T @ D @ X) @ X.T @ D @ pinv(I - P @ G) @ r

array([ 3.63970588,  2.97794118])