In [15]:
import numpy as np
from numpy.linalg import pinv

In [18]:
np.set_printoptions(precision=6, suppress=True)

In [2]:
import mdpy

In [3]:
ns = 5

I = np.eye(ns)
P = mdpy.rand_p(ns)

In [7]:
d = mdpy.stationary(P)
print(d)

[ 0.13692065  0.17804782  0.26470951  0.32311581  0.09720621]


In [ ]:
gm = 0.9

In [21]:
lst = []
for lm in np.linspace(0, 1, 11):
    lst.append(pinv(I - lm*gm*P) @ (I - gm*P))

In [24]:
for i in lst: print(i, end="\n\n")

[[ 0.803744 -0.182838 -0.217674 -0.204421 -0.098811]
 [-0.158508  0.749316 -0.217437 -0.226104 -0.047266]
 [-0.047605 -0.071447  0.764928 -0.352343 -0.193533]
 [-0.094246 -0.195956 -0.269217  0.681296 -0.021877]
 [-0.25802  -0.085854 -0.210956 -0.270669  0.925498]]

[[ 0.811328 -0.178963 -0.216665 -0.208797 -0.097013]
 [-0.153978  0.759075 -0.216583 -0.228358 -0.050265]
 [-0.054171 -0.077195  0.767005 -0.344054 -0.181695]
 [-0.094625 -0.191138 -0.263721  0.686895 -0.027522]
 [-0.243929 -0.091437 -0.210935 -0.268685  0.924876]]

[[ 0.819413 -0.174672 -0.21517  -0.212678 -0.094942]
 [-0.149093  0.769436 -0.215214 -0.230111 -0.053066]
 [-0.060341 -0.082846  0.769696 -0.334847 -0.16971 ]
 [-0.094949 -0.185822 -0.257605  0.693265 -0.032939]
 [-0.229399 -0.09665  -0.21036  -0.26616   0.92452 ]]

[[ 0.828121 -0.169821 -0.212978 -0.215814 -0.09252 ]
 [-0.143735  0.780546 -0.213121 -0.231112 -0.055592]
 [-0.066011 -0.088263  0.773216 -0.324457 -0.157498]
 [-0.095113 -0.179862 -0.250656  0.70067